-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgD02o/Pu3bWBADqux
+jjmR+gdnvd3u8coIJegzO8GyV+gCgYIKoZIzj0DAQehRANCAARricPXcG8oLm/j
JmO8v8ho/9dqUe6eGYMMPJJcPGV38ejv4BBlPMnTEQy2HTAlCKztD26fDy2EU6LL
qIQbFsKG
-----END PRIVATE KEY-----