# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'active_support'
fastlane_require 'active_support/core_ext/time'

#✅ 상수

SLACK_URL = ENV['SLACK_URL']

KEYCHAIN_NAME = ENV['KEYCHAIN_NAME']
KEYCHAIN_PASSWORD = ENV['KEYCHAIN_PASSWORD']

APP_IDENTIFIER = ENV['APP_IDENTIFIER']


default_platform(:ios)

platform :ios do
  lane :beta do
    begin
      sync_code_signing(type: "appstore")
  
      # 빌드번호(년월일시분초)
      increment_build_number(xcodeproj: "Fastlane-Example.xcodeproj", build_number: date_based_build_number)

      # 앱 빌드 및 TestFlight 업로드
      build_app(
        workspace: "Fastlane-Example.xcworkspace",
        scheme: "Fastlane-Example"
      )
      upload_to_testflight
      # 성공 메시지
      send_slack_message("✅ TestFlight 배포 됐습니다 😎")
    rescue => error
      # 실패 메시지
      send_slack_message("❌ TestFlight 배포 실패했습니다 😭\nError: #{error}", false)
      raise error # 실패를 Fastlane에 전달
    end
  end

  def send_slack_message(message, success = true)
    version = get_version_number(xcodeproj: "Fastlane-Example.xcodeproj") # Xcode 프로젝트의 버전 가져오기

    full_message = "iOS #{version}(#{date_based_build_number})\n\n#{message}"

    slack(
      message: full_message,
      success: success,
      slack_url: "#{SLACK_URL}"
    )
  end

  def date_based_build_number
    Time.now.in_time_zone("Asia/Seoul").strftime("%Y.%m%d.%H%M")
  end
end
